### PR TITLE
Fix Zephir syntax

### PR DESCRIPTION
**Pull request by AsterAI**
Zephir 0.3.1
Fixed 75% of syntax recognition collisions
Improved completion

[Zephir.zip](https://github.com/phalcon/zephir-idea-plugin/files/1009192/Zephir.zip)

### CODE REVIEW

**Comment by sergeyklay** [comment]
Is it ready to merge?

**Comment by AsterAI** [comment]
@sergeyklay Up to you. 
But i want reduce at least half syntax errors 
Also need fix extra space when completion insert arguments

**Comment by AsterAI** [comment]
Zephir 0.3.1 
Fixed 75% of syntax recognition collisions
Improved completion 

[Zephir.zip](https://github.com/phalcon/zephir-idea-plugin/files/1009187/Zephir.zip)

**Comment by AsterAI** [comment]
Ready to merge

**Comment by sergeyklay** [comment]
Thank you

**Pull request merged**
